### ISSUE TITLE
Development: New Field Location Type

### ISSUE THREAD

**Issue by BFARIAAL** [BFARIAAL/api-pdc-backend#18]
A requirement to introduce the field type to locations.
The possible types of locations will be:

PLANT
COMPOUND
PORT
ZONE

**Comment by BFARIAAL** [comment]
Assigning to Charlene

**Comment by Charhmwang** [comment]
[sql_quries.zip](https://github.com/BFARIAAL/api-pdc-backend/files/12816498/sql_quries.zip)

Please review/test the sql queries
