### ISSUE TITLE
Technical Analysis: Investigate possible approaches for Authentication on the API

### ISSUE THREAD

**Issue by BFARIAAL** [BFARIAAL/api-pdc-backend#32]
The scope of this ticket is to perform a technical analysis and determine possible approaches to authentication that can be implemented in the API. 
Upon completion a development ticket shall follow

**Comment by Charhmwang** [comment]
OAuth 2.0 is decided to be the most ideal approach for authentication in this system.
Please review the attached document.

[Authentication_analysis.docx](https://github.com/BFARIAAL/api-pdc-backend/files/12855704/Authentication_analysis.docx)
