### ISSUE TITLE
Technical Analysis: Modify Locations to include Country information

### ISSUE THREAD

**Issue by BFARIAAL** [BFARIAAL/api-pdc-backend#38]
The scope of this ticket is to perform a technical analysis on how to implement country information into our location details.

**NO DEVELOPMENT IS REQUIRED FOR THIS TICKET**: This is only the technical analysis and upon its conclusion a development ticket will be created.

**Comment by pedro-acsousa** [comment]
Technical Analysis Document

[TechnicalAnalysis_38.docx](https://github.com/BFARIAAL/api-pdc-backend/files/12927082/TechnicalAnalysis_38.docx)
