### ISSUE TITLE
Development: Modify Locations to include Country information

### ISSUE THREAD

**Issue by BFARIAAL** [BFARIAAL/api-pdc-backend#42]
The scope of this ticket is to perform the development analysed on ticket #38 (Please refer to the ticket to know how to proceed with the development)

**Comment by BFARIAAL** [comment]
PR Approved. Please attach the SQL queries to this ticket

**Comment by Charhmwang** [comment]
Update database SQL queries:
[Database_updates_42.docx](https://github.com/BFARIAAL/api-pdc-backend/files/12931864/Database_updates_42.docx)
