### ISSUE TITLE
Technical Analysis: Include location on the Vehicle API

### ISSUE THREAD

**Issue by BFARIAAL** [BFARIAAL/api-pdc-backend#45]
Perform a technical analysis on how to include detailed location information on the Vehicle API if the user requests it

**Comment by Charhmwang** [comment]
Please review the attached document containing the proposed solution plan, and whether the format meets the required technical analysis standards

[TechnicalAnalysis_45.docx](https://github.com/BFARIAAL/api-pdc-backend/files/13001839/TechnicalAnalysis_45.docx)

**Comment by BFARIAAL** [comment]
Moving back to In Progress.

The technical analysis suggests an approach to a new end point **/vehicles/by_id/{id}/location**. While this is a valid approach, it's not a scalable approach as we might want more details in other vehicle details (For example, if the vehicle has a location code that specifies the vehicle's assembly plant, we'd require two HTTP requests if we wanted both assembly plant location and current location details).
Please reanalyse the issue and try to come up with an approach that not only will be scalable to allow multiple detailed requests but also that will create a template that we can later use for similar detail requests.

**Comment by Charhmwang** [comment]
[TechnicalAnalysis_45.docx](https://github.com/BFARIAAL/api-pdc-backend/files/13040711/TechnicalAnalysis_45.docx)

This is my solution plan to make it a scalable approach based on the comment above.

**Comment by Charhmwang** [comment]
A solution designed corresponding to the scrum call today

[TechnicalAnalysis_45.docx](https://github.com/BFARIAAL/api-pdc-backend/files/13044356/TechnicalAnalysis_45.docx)

**Comment by Charhmwang** [comment]
This version included the database changes.
[TechnicalAnalysis_45.docx](https://github.com/BFARIAAL/api-pdc-backend/files/13052342/TechnicalAnalysis_45.docx)

**Comment by BFARIAAL** [comment]
TA reviewed. Please review the comments left in it for future TAs.

[TechnicalAnalysis_45.docx](https://github.com/BFARIAAL/api-pdc-backend/files/13068766/TechnicalAnalysis_45.docx)

 TA approved, moving to development
