### ISSUE TITLE
Technical Analysis: Introduce Assembly Plant information to the vehicle

### ISSUE THREAD

**Issue by BFARIAAL** [BFARIAAL/api-pdc-backend#48]
A new request to include Assembly Plant information to a vehicle as come.
An assembly plant represents the location in which the vehicle was assembled.
Please perform a technical analysis to determine the best way to implement this new field

**Comment by pedro-acsousa** [comment]
[TechnicalAnalysis_48.docx](https://github.com/BFARIAAL/api-pdc-backend/files/13029526/TechnicalAnalysis_48.docx)

Old Unused version

**Comment by pedro-acsousa** [comment]
[TechnicalAnalysis_48.docx](https://github.com/BFARIAAL/api-pdc-backend/files/13044708/TechnicalAnalysis_48.docx)

New Version

**Comment by BFARIAAL** [comment]
TA reviewed. Review comments and rewrite it
[TechnicalAnalysis_48.docx](https://github.com/BFARIAAL/api-pdc-backend/files/13068674/TechnicalAnalysis_48.docx)

**Comment by pedro-acsousa** [comment]
[TechnicalAnalysis_48 (3).docx](https://github.com/BFARIAAL/api-pdc-backend/files/13068848/TechnicalAnalysis_48.3.docx)

Technical Analysis has been reflected upon and rewritten

**Comment by BFARIAAL** [comment]
Final version of the TA. Approved for Developemnt
[TechnicalAnalysis_48.3 (1).docx](https://github.com/BFARIAAL/api-pdc-backend/files/13164124/TechnicalAnalysis_48.3.1.docx)
