### ISSUE TITLE
New Field Vehicle Status

### ISSUE THREAD

**Issue by BFARIAAL** [BFARIAAL/api-pdc-backend#6]
A requirement to introduce the field status to vehicles API PDC.
The possible status of the vehicle will be:

- INTRANS (Vehicle in transit)
- DLVRD (Vehicle has been delivered)
- INLOAD (Vehicle on a load)
- BUILT (Vehicle built)

**Comment by pedro-acsousa** [comment]
Bruno, can I consider the DataType to be enum('LOAD STATUS1', 'LOAD STATUS2'...)?

**Comment by BFARIAAL** [comment]
We need to create a new table in the db and link it to the vehicles table via a foreign key. Please write the SQL for the new table and the table update and send it to me via email
